#!/usr/bin/with-contenv bash
. /opt/scripts/install.rc;
__check_status;

echo "================================================================================"
echo "Converting templates."
echo "================================================================================"
echo ""
chmod 777 /opt/scripts/mm.pl;

dos2unix /opt/files/config/*;
if [ ! -f /opt/ServUO/ServUO.exe ]; then
    rm -r /opt/ServUO/Saves/Accounts/accounts.xml;
    mkdir -p /opt/ServUO/Saves/Accounts;
    chmod 777 /opt/ServUO/Saves/Accounts/;

    /opt/scripts/mm.pl /opt/files/config/;
else 
   echo "================================================================================"
   echo "Accounts.xml exists, skipping template conversion."
fi

lastexec=$?;
__exit $lastexec;

