#!/usr/bin/with-contenv bash
. /opt/scripts/install.rc

echo "================================================================================"
echo "Converting templates."
echo "================================================================================"
echo ""

chmod +x /opt/scripts/mm.pl

# Ensure config files are in Unix format
dos2unix /opt/files/config/*

ACCOUNT_FILE="/opt/ServUO/Saves/Accounts/accounts.xml"
ACCOUNT_DIR="/opt/ServUO/Saves/Accounts"
OTHER_DIR="/opt/ServUO/Scripts/Custom"
if [ ! -f "$ACCOUNT_FILE" ]; then
    mkdir -p "$ACCOUNT_DIR"
    mkdir -p "$OTHER_DIR"
    chmod 755 "$ACCOUNT_DIR"

    perl /opt/scripts/mm.pl /opt/files/config/ --verbose
else 
    echo "================================================================================"
    echo "accounts.xml exists, skipping template conversion."
fi
