#!/usr/bin/with-contenv bash
. /opt/scripts/install.rc
echo "================================================================================"
echo "Running Treads"
echo "================================================================================"
echo ""
echo "================================================================================"
echo "Building Other scripts..."
echo "================================================================================"
cd /opt/ServUO/
cp /opt/scripts/GeneratePasswordHash.cs /opt/ServUO/
mcs -r:ServUO.exe GeneratePasswordHash.cs
ADMIN_PASSWORD_HASH=$(mono GeneratePasswordHash.exe "$ADMIN_PASSWORD" | sed -n '2p')
echo "Generated password hash: $ADMIN_PASSWORD_HASH"
sed -i "s|<newCryptPassword>.*</newCryptPassword>|<newCryptPassword>${ADMIN_PASSWORD_HASH}</newCryptPassword>|" /opt/ServUO/Saves/Accounts/accounts.xml

/bin/su -s /bin/bash -c '/opt/scripts/run.sh'
