#!/usr/bin/with-contenv bash
. /opt/scripts/install.rc   

    echo "================================================================================"
    echo "Building ServUO scripts..."
    echo "================================================================================"
    export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools
    cd /opt/ServUO
    nuget install Newtonsoft.Json
    dotnet clean
    DOTNET_CLI_HOME=/opt/ServUO dotnet build --self-contained true -p:PublishSingleFile=false

    chmod -R 777 /opt/ServUO/
    chmod -R 777 /opt/ServUO/Saves